#!/usr/bin/env python3
"""update_workspace_readme.py — keep D:\\Hermes\\Nexis Aria Nexaris\\README.md in sync.

Scans the workspace (2 levels deep), regenerates the '## Current Structure'
section, and only rewrites the file when the tree actually changed.
"""
import argparse
import hashlib
import os
import sys

ROOT = r"D:\Hermes\Nexis Aria Nexaris"
README = os.path.join(ROOT, "README.md")
SKIP_DIRS = {"__pycache__", ".git", ".venv", "venv", "node_modules", ".pytest_cache"}

LEGEND = \"\"\"# Nexis Aria Nexaris Workspace

Welcome to the central hub for Nexis. This workspace serves as the deep storage and organizational layer for my activities.

## Map & Legend
- `/projects` - Individual project folders. Each MUST have a `README.md` for state tracking.
- `/scripts` - Reusable automation and utility scripts.
- `/docs` - Structured intelligence. `/specs` (Requirements) and `/process` (Plans/How-tos).
- `/knowledge` - Deep research, reference materials, and external notes.
- `/assets` - Media, images, and raw resources.
- `/output` - Final deliverables and results (Nexaris Family Standard).
- `/templates` - Reusable scaffolds for code and documentation.
- `/inbox` - Temporary landing zone for raw data.
- `/archive` - Versioned backup of completed or legacy work.

## Operational Logic
This workspace is a supplement to the Hermes Profile Memory.
- **Fast Memory:** Facts, rules, and paths are stored in the Hermes Profile.
- **Deep Storage:** Large files, research, and project history live here.
- **Continuity:** Every project folder is a \"save point\" via its local README.

## Current Structure
_Auto-generated by scripts/update_workspace_readme.py - do not edit by hand._
\"\"\"


def build_tree(root: str, depth: int = 2) -> str:
    lines = ["```text", ROOT + "\\"]
    entries = sorted(
        (e for e in os.scandir(root) if e.name not in SKIP_DIRS),
        key=lambda e: (e.is_file(), e.name.lower()),
    )
    for i, entry in enumerate(entries):
        last = i == len(entries) - 1
        branch = "+-- " if last else "|-- "
        lines.append(branch + entry.name)
        if entry.is_dir() and depth > 1:
            subs = sorted(
                (s for s in os.scandir(entry.path) if s.name not in SKIP_DIRS),
                key=lambda s: (s.is_file(), s.name.lower()),
            )
            for j, sub in enumerate(subs):
                sub_last = j == len(subs) - 1
                lines.append(
                    ("    " if last else "|   ")
                    + ("`-- " if sub_last else "|-- ")
                    + sub.name
                )
    lines.append("```")
    return "\\n".join(lines)


def current_tree_hash(root: str) -> str:
    parts = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        rel = os.path.relpath(dirpath, root)
        depth = 0 if rel == "." else rel.count(os.sep) + 1
        if depth > 2:
            dirnames[:] = []
            continue
        for f in sorted(filenames):
            if f in SKIP_DIRS:
                continue
            p = os.path.join(dirpath, f)
            try:
                st = os.stat(p)
                parts.append(f"{os.path.relpath(p, root)}|{st.st_size}")
            except OSError:
                pass
    return hashlib.sha256("\\n".join(parts).encode()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync workspace README structure tree.")
    parser.add_argument("--check", action="store_true", help="report changes without writing")
    args = parser.parse_args()

    new_hash = current_tree_hash(ROOT)
    state_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".readme_tree_state")

    old_hash = ""
    if os.path.exists(state_file):
        with open(state_file, "r", encoding="utf-8") as f:
            old_hash = f.read().strip()

    content = LEGEND + build_tree(ROOT)
    if args.check:
        if old_hash != new_hash:
            print("WORKSPACE CHANGED: README.md needs refresh (run update_workspace_readme.py)")
            return 1
        return 0

    if old_hash == new_hash and os.path.exists(README):
        with open(README, "r", encoding="utf-8") as f:
            if f.read() == content:
                return 0
    with open(README, "w", encoding="utf-8") as f:
        f.write(content)
    with open(state_file, "w", encoding="utf-8") as f:
        f.write(new_hash)
    print("README.md updated: " + ROOT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
